platform :ios, '10.0'

target 'TheMessageApp' do
  use_frameworks!
  
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  target 'TheMessageAppTests' do
    inherit! :search_paths
  end
end
