platform :ios, '10.0'

target 'TheMessagesApp' do
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.9.0'
  pod 'Crashlytics', '~> 3.12.0'

  target 'TheMessagesAppTests' do
    inherit! :search_paths
    pod 'Quick', :git => 'https://github.com/Quick/Quick'
    pod 'Nimble', :git => 'https://github.com/Quick/Nimble'
  end
end
